@baseUrl = http://localhost:4001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pcm5hQG1haWwuY29tIiwidXNlcklkIjoiNjRhZjg4ODRmMmE2ZDRmNzJiYjlkOGUwIiwiaWF0IjoxNjg5NTc1MzU0LCJleHAiOjE2OTAwNzkzNTR9.mVQIRfKWz3FTnUezCFEPulaOn_vbDpqWl49G6YHIFKA

### Create Golongan
POST {{baseUrl}}/golongan
Content-Type: application/json
x-access-token: {{token}}

{
  "nama": "Golongan 01",
  "tunjanganGolongan": 1000000
}

### List Golongan
GET {{baseUrl}}/golongan
Content-Type: application/json
x-access-token: {{token}}

### Detail Golongan
GET {{baseUrl}}/golongan/64afcdc906deef93319ad2d3
Content-Type: application/json
x-access-token: {{token}}


### Edit Golongan
PUT {{baseUrl}}/golongan/64afcdc906deef93319ad2d3
Content-Type: application/json
x-access-token: {{token}}

{
  "nama": "Golongan A01",
  "tunjanganGolongan": 1600000
}

### Delete Jabatan
DELETE {{baseUrl}}/jabatan/64afcdc906deef93319ad2d3
Content-Type: application/json
x-access-token: {{token}}