@baseUrl = http://localhost:4001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pcm5hQG1haWwuY29tIiwidXNlcklkIjoiNjRhZjg4ODRmMmE2ZDRmNzJiYjlkOGUwIiwiaWF0IjoxNjg5MjMzMTM2LCJleHAiOjE2ODk3MzcxMzZ9.6KHLHERwNYssocCeiEuSqB_9Zs_nM1grhGt7eNTn_SQ

### Create Jabatan
POST {{baseUrl}}/jabatan
Content-Type: application/json
x-access-token: {{token}}

{
  "nama": "Manager",
  "tunjanganJabatan": 50000,
  "tunjanganKeluarga": 250000,
  "tunjanganAnak": 120000
}


### List Jabatan
GET {{baseUrl}}/jabatan
Content-Type: application/json
x-access-token: {{token}}