@baseUrl = http://localhost:4001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pcm5hQG1haWwuY29tIiwidXNlcklkIjoiNjRhZjg4ODRmMmE2ZDRmNzJiYjlkOGUwIiwiaWF0IjoxNjg5NTc1MzU0LCJleHAiOjE2OTAwNzkzNTR9.mVQIRfKWz3FTnUezCFEPulaOn_vbDpqWl49G6YHIFKA

### Sign in
POST {{baseUrl}}/users/signin
Content-Type: application/json

{
  "email": "mirna@mail.com",
  "password": "123123123"
}

### Create New User
POST {{baseUrl}}/users
Content-Type: application/json
x-access-token: {{token}}

{
  "email": "mirna@mail.com",
  "password": "123123123",
  "lastName": "Fikania",
  "firstName": "Mirna"
}